#! /bin/sh

for pic in `ls pic*.aspic` ; do
  base=`expr match $pic '\([^.]\+\)'`
  ../src/aspic -ov -creator PH -date 'Not set' -title $base $pic $base.eps
done 

xfpt aspic.xfpt
sdop aspic.xml
ps2pdf aspic.ps
